"""

Revision ID: 02f76f246b97
Revises: 429886c32b64
Create Date: 2021-07-21 12:47:04.252560+07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f76f246b97'
down_revision = '429886c32b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower_following',
    sa.Column('following_id', sa.BIGINT(), nullable=False),
    sa.Column('follower_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('following_id', 'follower_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower_following')
    # ### end Alembic commands ###
