"""

Revision ID: 25a53e679336
Revises: 
Create Date: 2021-07-21 11:30:32.824117+07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a53e679336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('id_is_active', 'user', ['id', 'is_active'], unique=False)
    op.create_index('username_is_active', 'user', ['username', 'is_active'], unique=False)
    op.create_table('activity',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), server_default='0', nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('is_crossed', sa.BOOLEAN(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='activity_user_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('name', 'activity', ['name'], unique=False)
    op.create_index('priority', 'activity', ['priority'], unique=False)
    op.create_table('private_message',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.BIGINT(), nullable=False),
    sa.Column('receiver_id', sa.BIGINT(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name='receiver_fk'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='sender_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('private_message')
    op.drop_index('priority', table_name='activity')
    op.drop_index('name', table_name='activity')
    op.drop_table('activity')
    op.drop_index('username_is_active', table_name='user')
    op.drop_index('id_is_active', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
