"""

Revision ID: 429886c32b64
Revises: 985abc5802c1
Create Date: 2021-07-21 12:41:53.970314+07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '429886c32b64'
down_revision = '985abc5802c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower_following')
    op.drop_column('private_message', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('private_message', sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
    op.create_table('follower_following',
    sa.Column('follower_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('following_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='follower_following_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], name='follower_following_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
