"""test

Revision ID: 68f39482fc18
Revises: c4abe7565a2b
Create Date: 2021-07-21 00:58:02.374393+07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68f39482fc18'
down_revision = 'c4abe7565a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
