"""test

Revision ID: 743d27407a7a
Revises: 68f39482fc18
Create Date: 2021-07-21 01:02:17.661779+07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743d27407a7a'
down_revision = '68f39482fc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
