"""test

Revision ID: 8d5dd547c8e8
Revises: a622501c9fcb
Create Date: 2021-07-21 00:31:31.582924+07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5dd547c8e8'
down_revision = 'a622501c9fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), server_default='0', nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('is_crossed', sa.BOOLEAN(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('name', 'activity', ['name'], unique=False)
    op.create_index('priority', 'activity', ['priority'], unique=False)
    op.create_index('user_id_name', 'activity', ['user_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id_name', table_name='activity')
    op.drop_index('priority', table_name='activity')
    op.drop_index('name', table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
