"""test

Revision ID: c4abe7565a2b
Revises: 8d5dd547c8e8
Create Date: 2021-07-21 00:49:30.555721+07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4abe7565a2b'
down_revision = '8d5dd547c8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'activity', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='foreignkey')
    # ### end Alembic commands ###
